---
title: CO2 Bar Chart Race
author: Michael Metzler
date: '2019-04-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 6, tidy = "styler", animation.hook = "gifski", df_print = "kable")
```

```{r}
library(tidyverse)
```

```{r message=FALSE}
wb_df <- read_csv("C:/datasets/WDI/WDIData.csv")
names(wb_df) <- names(wb_df) %>% tolower() %>% str_replace(" ", "_")
country_df <- read_csv("C:/datasets/WDI/WDICountry.csv")
names(country_df) <- names(country_df) %>% tolower() %>% str_replace_all(" ", "_")
```

```{r}
# Lookup table mapping country codes to names
country_names <- country_df %>%
  pull(short_name) %>%
  set_names(country_df %>% pull(country_code)) %>%
  sort()
region_lookup <- country_df%>%
  filter(!is.na(region))%>%
  (function(x)x%>%pull(region) %>% set_names(x %>% pull(country_code)))
```

```{r}
world <- wb_df %>%
  select( -country_name, -indicator_name, -x64) %>%
  filter(country_code %in% names(region_lookup)) %>%
  gather(key = "year", value = "value", -country_code, -indicator_code) %>%
  mutate(year = as.integer(year)) %>%
  spread(indicator_code, value)
```

```{r}
long_co2_per_cap <- world %>% 
  select(country_code, year, "EN.ATM.CO2E.PC") %>%
  rename(co2_per_cap = "EN.ATM.CO2E.PC")

good_years <- long_co2_per_cap %>%
  group_by(year) %>%
  summarise(has_data = any(!is.na(co2_per_cap))) %>%
  filter(has_data) %>%
  pull(year)

long_co2_per_cap <-long_co2_per_cap %>% filter(year %in% good_years)
```

```{r}
long_co2_per_cap <- long_co2_per_cap %>%
  group_by(year) %>%
  arrange(desc(co2_per_cap)) %>%
  mutate(ranking = row_number()) %>%
  filter(ranking <= 10) %>%
  ungroup()
```

```{r}
label_regex <- "[:digit:]+(?:[.][:digit:]{0,2})?+"

years <- long_co2_per_cap %>% pull(year)%>% unique()

library(gganimate)
library(ggfittext)
co2_per_cap_race <- long_co2_per_cap %>%
  ggplot(aes(xmax = 11 - ranking, xmin = 10.10 - ranking, group = country_code)) +
  geom_rect(
    aes(
      ymin = 0, ymax = co2_per_cap,
      fill = region_lookup[country_code]
    )
  ) +
  geom_fit_text(
    aes(label = country_names[country_code], ymin = -10, ymax = 0),
    place = "right",
    height = 10,
    width = .9,
    reflow = TRUE
  ) +
  geom_fit_text(
    aes(label = co2_per_cap, ymin = co2_per_cap, ymax = co2_per_cap + 10),
    formatter = function(x) str_extract(x, label_regex),
    place = "left",
    height = 10,
    width = .9
  ) +
  coord_flip(clip = "off") +
  scale_fill_brewer(name = "Region",type = "qual", palette = "Set1") +
  theme(
    panel.background = element_rect(fill = "white"),
    legend.position = c(.9,.2),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    plot.title = element_text(size = 24, vjust = .5, hjust = .5),
    plot.subtitle = element_text(size = 18, vjust = .5, hjust = .5),
    legend.title = element_text(face = "bold"),
  ) +
  transition_time(year) +
  enter_manual(
    "1" = function(df) mutate(df, xmin = -.9, xmax = 0, ymin = 0, ymax = 0),
    "2" = function(df) mutate(df, xmin = -.9, xmax = 0),
    "3" = function(df) 
      mutate(
        df,
        xmin = -.9, xmax = 0,
        ymin = 0, ymax = 5,
        label = 0
      )
  ) +
  exit_manual(
    "1" = function(df) mutate(df, xmin = -.9, xmax = 0, ymin = 0, ymax = 0),
    "2" = function(df) mutate(df, xmin = -.9, xmax = 0),
    "3" = function(df)
      mutate(
        df,
        xmin = -.9, xmax = 0,
        ymin = 0, ymax = 5,
        label = 0
      )
  ) +
  ease_aes("sine-in-out") +
  labs(
    title = "CO2 Emissions Per Capita",
    subtitle = "Year: {round(frame_time,0)}"
  )

animate(co2_per_cap_race, nframes = 20*length(years), fps = 20, end_pause = 100, width = 1280, height = 720)
```

